use super::{ChatOptions, GenerateOptions, LlmProvider, LlmResponse, ModelInfo, RunningModel};
use anyhow::Result;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::{
    net::{IpAddr, Ipv6Addr},
    time::{Duration, Instant},
};
use tracing::{debug, error};

/// The local Ollama API endpoint used when neither configuration nor
/// `OLLAMA_HOST` provides an endpoint. Use IPv4 explicitly: on some Windows
/// systems `localhost` resolves to `::1` first while Ollama is only listening
/// on IPv4, producing an opaque connection failure.
pub const DEFAULT_OLLAMA_ENDPOINT: &str = "http://127.0.0.1:11434";

const DEFAULT_OLLAMA_PORT: u16 = 11434;

#[derive(Debug, Clone)]
pub struct OllamaProvider {
    base_url: String,
    client: Client,
    /// Separate client for STREAMING generations. It has NO whole-request
    /// timeout: a healthy local generation can legitimately run for minutes on
    /// slow hardware, and a total cap (the old 300s) killed long-but-progressing
    /// streams mid-flight — the cause of the "read streaming chunk from Ollama"
    /// error. Stalls are instead bounded per-chunk in `generate_streaming`.
    stream_client: Client,
}

/// Max idle time between streamed chunks before we declare the stream stalled.
/// Generous enough to cover a cold model load (first token), tight enough to
/// catch a genuinely-hung Ollama or a model too large to ever load.
const STREAM_IDLE_TIMEOUT: Duration = Duration::from_secs(180);

/// Resolve an Ollama endpoint from an explicit value and, only when that value
/// is blank or one of the historical defaults, `OLLAMA_HOST`. This keeps an
/// explicit remote endpoint authoritative while letting the standard Ollama
/// environment variable work on a first-run configuration.
pub fn resolve_ollama_endpoint(configured: &str) -> Result<String> {
    let environment_host = std::env::var("OLLAMA_HOST").ok();
    resolve_ollama_endpoint_with_host(configured, environment_host.as_deref())
}

fn resolve_ollama_endpoint_with_host(
    configured: &str,
    environment_host: Option<&str>,
) -> Result<String> {
    let candidate = if is_default_or_blank_endpoint(configured) {
        environment_host
            .filter(|host| !host.trim().is_empty())
            .unwrap_or(DEFAULT_OLLAMA_ENDPOINT)
    } else {
        configured
    };

    normalize_ollama_endpoint(candidate)
}

fn is_default_or_blank_endpoint(endpoint: &str) -> bool {
    let endpoint = endpoint.trim().trim_end_matches('/');
    endpoint.is_empty()
        || endpoint.eq_ignore_ascii_case(DEFAULT_OLLAMA_ENDPOINT)
        // Retain compatibility with config files generated by older releases.
        || endpoint.eq_ignore_ascii_case("http://localhost:11434")
        || endpoint.eq_ignore_ascii_case("localhost:11434")
}

/// Make Ollama's permissive host setting safe to use as an HTTP client base
/// URL. `OLLAMA_HOST` is also commonly used as the daemon's *bind* address,
/// where `0.0.0.0` and `::` mean all interfaces. Those are not reliable client
/// targets (especially on Windows), so map them to IPv4 loopback instead.
fn normalize_ollama_endpoint(raw_endpoint: &str) -> Result<String> {
    let raw_endpoint = raw_endpoint.trim();
    let has_explicit_scheme = raw_endpoint.contains("://");
    let candidate = if has_explicit_scheme {
        raw_endpoint.to_owned()
    } else {
        // A bare IPv6 address requires brackets once it becomes the host part
        // of a URL. Bracketed `OLLAMA_HOST` values such as `[::]:11434` are
        // already valid and pass through unchanged.
        let host = if raw_endpoint.parse::<Ipv6Addr>().is_ok() {
            format!("[{raw_endpoint}]")
        } else {
            raw_endpoint.to_owned()
        };
        format!("http://{host}")
    };

    let mut endpoint = reqwest::Url::parse(&candidate)
        .map_err(|e| anyhow::anyhow!("invalid Ollama endpoint `{raw_endpoint}`: {e:#}"))?;

    if !matches!(endpoint.scheme(), "http" | "https") {
        anyhow::bail!(
            "invalid Ollama endpoint `{raw_endpoint}`: expected an http:// or https:// URL"
        );
    }
    if endpoint.host_str().is_none() {
        anyhow::bail!("invalid Ollama endpoint `{raw_endpoint}`: missing host");
    }
    if endpoint.query().is_some() || endpoint.fragment().is_some() {
        anyhow::bail!(
            "invalid Ollama endpoint `{raw_endpoint}`: query strings and fragments are not supported"
        );
    }

    // Host-only values (`localhost`, `192.168.1.25`, `[::1]`) mean the local
    // Ollama port. Keep HTTPS's conventional 443 for deliberate remote HTTPS
    // endpoints, but use 11434 for HTTP or a scheme-less Ollama host.
    if endpoint.port().is_none() && (!has_explicit_scheme || endpoint.scheme() == "http") {
        endpoint.set_port(Some(DEFAULT_OLLAMA_PORT)).map_err(|_| {
            anyhow::anyhow!("Ollama endpoint `{raw_endpoint}` does not support a port")
        })?;
    }

    // `localhost` is conventionally loopback, but it is still name-resolved
    // by the OS. Screen crops and microphone-derived context use this endpoint
    // as a privacy boundary, so pin it to a literal loopback address instead
    // of trusting a mutable hosts/DNS mapping.
    let is_localhost = endpoint
        .host_str()
        .is_some_and(|host| host.eq_ignore_ascii_case("localhost"));
    if is_localhost {
        endpoint.set_host(Some("127.0.0.1")).map_err(|e| {
            anyhow::anyhow!("replace localhost Ollama host `{raw_endpoint}`: {e:#}")
        })?;
    }

    let is_bind_all = endpoint
        .host_str()
        .map(|host| host.trim_matches(|c| c == '[' || c == ']'))
        .is_some_and(|host| host == "0.0.0.0" || host == "::");
    if is_bind_all {
        endpoint
            .set_host(Some("127.0.0.1"))
            .map_err(|e| anyhow::anyhow!("replace bind-all Ollama host `{raw_endpoint}`: {e:#}"))?;
    }

    // `Url` canonicalizes a root path to `/`. Store an endpoint without that
    // trailing slash so every API URL is exactly `<base>/api/...`, never `//api`.
    Ok(endpoint.as_str().trim_end_matches('/').to_owned())
}

/// Whether an already-normalized Ollama endpoint is loopback-only.
///
/// This is intentionally public because callers that handle sensitive local
/// inputs (microphone recordings, screen crops, or workspace evidence) must
/// be able to fail closed when a user has configured Ollama to point at a
/// remote machine.  The provider itself permits a deliberate remote endpoint
/// for ordinary text generation; it must not make that choice on behalf of a
/// privacy-sensitive feature.
pub fn is_local_ollama_endpoint(endpoint: &str) -> bool {
    reqwest::Url::parse(endpoint)
        .ok()
        .and_then(|url| url.host_str().map(str::to_owned))
        .map(|host| {
            let host = host.trim_matches(|c| c == '[' || c == ']');
            host.parse::<IpAddr>()
                .map(|address| address.is_loopback())
                .unwrap_or(false)
        })
        .unwrap_or(false)
}

fn build_ollama_client(endpoint: &str, bypass_proxy: bool, streaming: bool) -> Result<Client> {
    let client = if streaming {
        Client::builder()
            // No total timeout — streaming is bounded per-chunk, not overall.
            .connect_timeout(Duration::from_secs(15))
            .tcp_keepalive(Duration::from_secs(30))
    } else {
        Client::builder()
            .timeout(Duration::from_secs(300))
            .connect_timeout(Duration::from_secs(15))
    };
    let client = if bypass_proxy {
        // Do not let HTTP(S)_PROXY turn a local Ollama request into a proxy
        // request. That is a frequent source of Windows-only connection errors.
        debug!("Ollama endpoint is local; bypassing HTTP proxy settings: {endpoint}");
        client.no_proxy()
    } else {
        client
    };
    // Treat a model endpoint as an exact trust boundary. In particular, a
    // loopback Ollama server must never be able to redirect an attached image
    // or screen crop to a remote host. Deliberate remote Ollama users also get
    // clearer failures instead of a silent cross-origin follow-up.
    let client = client.redirect(reqwest::redirect::Policy::none());
    let kind = if streaming { "streaming" } else { "HTTP" };
    client
        .build()
        .map_err(|e| anyhow::anyhow!("build {kind} reqwest client for Ollama at {endpoint}: {e:#}"))
}

fn ollama_error(operation: &str, endpoint: &str, error: impl std::fmt::Display) -> anyhow::Error {
    anyhow::anyhow!("{operation} at {endpoint}: {error:#}")
}

#[derive(Debug, Serialize)]
struct GenerateRequest {
    model: String,
    prompt: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    system: Option<String>,
    stream: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    options: Option<GenerateOptionsDto>,
    #[serde(skip_serializing_if = "Option::is_none")]
    context: Option<Vec<i32>>,
    /// Ollama's keep_alive — accepts "30m", "1h", "0", or seconds as a number.
    /// We always send it because the server default (5m) bites every model switch.
    #[serde(skip_serializing_if = "Option::is_none")]
    keep_alive: Option<String>,
    /// Base64 images for multimodal models (vision).
    #[serde(skip_serializing_if = "Option::is_none")]
    images: Option<Vec<String>>,
    /// Reasoning toggle for thinking-capable models (Ollama `think`).
    #[serde(skip_serializing_if = "Option::is_none")]
    think: Option<bool>,
    /// Ollama `format` parameter (v0.5+). Either the literal string `"json"`
    /// for free-form valid JSON, or a full JSON Schema document for
    /// schema-constrained decoding. We pass it through as raw JSON so
    /// callers can hand us either form.
    #[serde(skip_serializing_if = "Option::is_none")]
    format: Option<serde_json::Value>,
}

#[derive(Debug, Serialize)]
struct GenerateOptionsDto {
    #[serde(skip_serializing_if = "Option::is_none")]
    temperature: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    top_p: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    top_k: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    num_ctx: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    num_gpu: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    main_gpu: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    repeat_penalty: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    stop: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    seed: Option<i64>,
}

#[derive(Debug, Serialize)]
struct ChatRequest {
    model: String,
    messages: Vec<ChatMessageDto>,
    stream: bool,
    options: Option<ChatOptionsDto>,
}

#[derive(Debug, Serialize, Deserialize)]
struct ChatMessageDto {
    role: String,
    content: String,
}

#[derive(Debug, Serialize)]
struct ChatOptionsDto {
    temperature: Option<f32>,
    top_p: Option<f32>,
    num_ctx: Option<usize>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)] // `context`/`total_duration` arrive from Ollama; surfaced in Debug only
struct GenerateResponse {
    response: String,
    /// Reasoning tokens from thinking-capable models (Ollama `thinking`),
    /// streamed separately from `response`. Absent for non-reasoning models.
    #[serde(default)]
    thinking: Option<String>,
    model: String,
    done: bool,
    context: Option<Vec<i32>>,
    total_duration: Option<u64>,
    eval_count: Option<usize>,
    prompt_eval_count: Option<usize>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)] // `total_duration` arrives from Ollama; surfaced in Debug only
struct ChatResponse {
    message: ChatMessageDto,
    model: String,
    done: bool,
    total_duration: Option<u64>,
    eval_count: Option<usize>,
    prompt_eval_count: Option<usize>,
}

#[derive(Debug, Deserialize)]
struct ModelsResponse {
    models: Vec<ModelDto>,
}

#[derive(Debug, Deserialize)]
struct ModelDto {
    name: String,
    size: u64,
    modified_at: String,
    digest: String,
}

/// `/api/ps` response. Lists models currently loaded into VRAM/RAM.
#[derive(Debug, Deserialize)]
struct PsResponse {
    models: Vec<PsModelDto>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct PsModelDto {
    name: String,
    model: String,
    size: u64,
    /// Bytes of *VRAM* this model is consuming. May be 0 on CPU-only.
    size_vram: Option<u64>,
    digest: String,
    expires_at: Option<String>,
}

impl OllamaProvider {
    /// Build a provider against `base_url`. The endpoint is normalized before
    /// use; this panics only for an invalid endpoint or a reqwest client-init
    /// failure. Library callers that need a recoverable error can use
    /// [`Self::try_new`].
    pub fn new(base_url: impl AsRef<str>) -> Self {
        Self::try_new(base_url)
            .unwrap_or_else(|e| panic!("ollama-forge: could not initialize Ollama provider: {e:#}"))
    }

    /// Fallible variant — for callers (libraries, tests) that don't want to
    /// take down the process on a TLS-init failure.
    pub fn try_new(base_url: impl AsRef<str>) -> Result<Self> {
        let base_url = resolve_ollama_endpoint(base_url.as_ref())?;
        let bypass_proxy = is_local_ollama_endpoint(&base_url);
        let client = build_ollama_client(&base_url, bypass_proxy, false)?;
        let stream_client = build_ollama_client(&base_url, bypass_proxy, true)?;

        Ok(Self {
            base_url,
            client,
            stream_client,
        })
    }

    fn api_url(&self, path: &str) -> String {
        debug_assert!(path.starts_with('/'));
        format!("{}{path}", self.base_url)
    }

    /// Stream a generate request, calling `on_token` with each text chunk as
    /// it arrives. Returns the total number of bytes streamed. Used by
    /// `forge chat` so users see tokens flow in instead of waiting 20s for a
    /// buffered blob.
    ///
    /// Implementation note: we use `Response::chunk()` rather than
    /// `bytes_stream()` to avoid pulling in the `futures` crate just for
    /// `StreamExt`. NDJSON line-buffering is done by hand because chunks
    /// can split a line in half.
    pub async fn generate_streaming<F>(
        &self,
        opts: GenerateOptions,
        mut on_token: F,
    ) -> Result<usize>
    where
        F: FnMut(&str),
    {
        // Delegate, dropping the reasoning stream (CLI callers want answer text).
        self.generate_streaming_parts(opts, |t| on_token(t), |_| {})
            .await
    }

    /// Streaming generate that surfaces the answer text (`on_token`) and the
    /// model's REASONING tokens (`on_thinking`) separately. Reasoning only
    /// arrives for thinking-capable models with `think: true` — we never invent
    /// it. Returns total answer bytes.
    pub async fn generate_streaming_parts<F, G>(
        &self,
        opts: GenerateOptions,
        mut on_token: F,
        mut on_thinking: G,
    ) -> Result<usize>
    where
        F: FnMut(&str),
        G: FnMut(&str),
    {
        let mut request = Self::build_generate_request(&opts);
        request.stream = true;
        let endpoint = self.api_url("/api/generate");

        let resp = self
            .stream_client
            .post(endpoint.as_str())
            .json(&request)
            .send()
            .await
            .map_err(|e| ollama_error("send streaming generate request", &endpoint, e))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            anyhow::bail!(
                "Ollama API error {status} from {endpoint}: {body}\n\
                 Hint: is `ollama serve` running at {} and is `{}` pulled?",
                self.base_url,
                opts.model
            );
        }

        let mut response = resp;
        let mut buf: Vec<u8> = Vec::with_capacity(4096);
        let mut total = 0usize;
        // Per-chunk IDLE timeout (not a whole-request cap): a slow-but-healthy
        // stream keeps delivering bytes and runs as long as it needs; only a
        // genuine stall trips this, with an actionable message instead of the
        // old cryptic 300s failure.
        loop {
            let chunk = match tokio::time::timeout(STREAM_IDLE_TIMEOUT, response.chunk()).await {
                Ok(Ok(Some(c))) => c,
                Ok(Ok(None)) => break,
                Ok(Err(e)) => {
                    return Err(ollama_error("read streaming chunk from Ollama", &endpoint, e));
                }
                Err(_) => anyhow::bail!(
                    "Ollama at {endpoint} produced no output for {}s — model `{}` is likely too large for this \
                     machine (still cold-loading) or Ollama hung. Pick a smaller model that fits \
                     your VRAM (`forge models --fits-only`) or keep it warm and retry.",
                    STREAM_IDLE_TIMEOUT.as_secs(),
                    opts.model
                ),
            };
            buf.extend_from_slice(&chunk);
            // Drain complete lines from buf — Ollama emits one JSON object per line.
            while let Some(nl) = buf.iter().position(|b| *b == b'\n') {
                let line: Vec<u8> = buf.drain(..=nl).collect();
                let trimmed = std::str::from_utf8(&line).map(|s| s.trim()).unwrap_or("");
                if trimmed.is_empty() {
                    continue;
                }
                let parsed: GenerateResponse = match serde_json::from_str(trimmed) {
                    Ok(p) => p,
                    Err(e) => {
                        debug!("skipping malformed NDJSON line: {e}");
                        continue;
                    }
                };
                if let Some(t) = parsed.thinking.as_deref() {
                    if !t.is_empty() {
                        on_thinking(t);
                    }
                }
                if !parsed.response.is_empty() {
                    total += parsed.response.len();
                    on_token(&parsed.response);
                }
                if parsed.done {
                    return Ok(total);
                }
            }
        }
        Ok(total)
    }

    /// Look up a model's manifest digest. This is the SHA the replay log
    /// records — pinning it lets `forge replay` detect when the user has
    /// pulled a different version of the same tag.
    ///
    /// Strategy: query `/api/tags` (the list endpoint) and find the entry
    /// matching `model`. Older Ollama versions don't expose `digest` on
    /// `/api/show` reliably; the list endpoint has been stable since v0.1.x.
    /// Returns `None` (not an error) if Ollama is unreachable, so callers
    /// can fall back gracefully.
    pub async fn model_digest(&self, model: &str) -> Option<String> {
        let models = self.list_models().await.ok()?;
        models
            .into_iter()
            .find(|m| m.name == model)
            .map(|m| m.digest)
            .filter(|d| !d.is_empty())
    }

    /// Raw `/api/show` document for a model. Used by the UI to surface the
    /// model's context window and capabilities (e.g. `tools`, `thinking`,
    /// `vision`) in the picker — all local, no inference. Returns the parsed
    /// JSON so the caller can pull whatever fields it needs.
    pub async fn show(&self, model: &str) -> Result<serde_json::Value> {
        let endpoint = self.api_url("/api/show");
        let resp = self
            .client
            .post(endpoint.as_str())
            .json(&serde_json::json!({ "name": model }))
            .send()
            .await
            .map_err(|e| ollama_error("send /api/show request to Ollama", &endpoint, e))?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            anyhow::bail!("Ollama /api/show returned {status} from {endpoint}: {body}");
        }
        resp.json()
            .await
            .map_err(|e| ollama_error("parse /api/show response from Ollama", &endpoint, e))
    }

    /// Models currently resident in VRAM/RAM (Ollama `/api/ps`).
    /// Returns `(name, vram_bytes, expires_at)` for each loaded model.
    pub async fn running_models(&self) -> Result<Vec<RunningModel>> {
        let endpoint = self.api_url("/api/ps");
        let resp = self
            .client
            .get(endpoint.as_str())
            .send()
            .await
            .map_err(|e| ollama_error("send /api/ps request to Ollama", &endpoint, e))?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            anyhow::bail!("Ollama /api/ps returned {status} from {endpoint}: {body}");
        }
        let parsed: PsResponse = resp
            .json()
            .await
            .map_err(|e| ollama_error("parse /api/ps response from Ollama", &endpoint, e))?;
        Ok(parsed
            .models
            .into_iter()
            .map(|m| RunningModel {
                name: m.name,
                size_vram_bytes: m.size_vram.unwrap_or(0),
                expires_at: m.expires_at,
            })
            .collect())
    }

    pub async fn health_check(&self) -> Result<bool> {
        let endpoint = self.api_url("/api/tags");
        match self.client.get(endpoint.as_str()).send().await {
            Ok(resp) => Ok(resp.status().is_success()),
            Err(e) => {
                error!("Ollama health check failed at {endpoint}: {e:#}");
                Ok(false)
            }
        }
    }

    fn build_generate_request(opts: &GenerateOptions) -> GenerateRequest {
        let options = GenerateOptionsDto {
            temperature: opts.temperature,
            top_p: opts.top_p,
            top_k: opts.top_k,
            num_ctx: opts.num_ctx,
            num_gpu: opts.num_gpu,
            main_gpu: opts.main_gpu,
            repeat_penalty: opts.repeat_penalty,
            stop: opts.stop.clone(),
            seed: opts.seed,
        };

        GenerateRequest {
            model: opts.model.clone(),
            prompt: opts.prompt.clone(),
            system: opts.system.clone(),
            stream: opts.stream,
            options: Some(options).filter(|o| {
                o.temperature.is_some()
                    || o.top_p.is_some()
                    || o.top_k.is_some()
                    || o.num_ctx.is_some()
                    || o.num_gpu.is_some()
                    || o.main_gpu.is_some()
                    || o.repeat_penalty.is_some()
                    || o.stop.is_some()
                    || o.seed.is_some()
            }),
            context: None,
            keep_alive: opts.keep_alive.clone(),
            images: opts.images.clone().filter(|v| !v.is_empty()),
            think: opts.think,
            format: opts.format.clone(),
        }
    }

    /// True if the model advertises the `thinking` capability (Ollama
    /// `/api/show`). Used to enable reasoning output only where it's real — we
    /// never fabricate a thinking transcript for non-reasoning models.
    pub async fn supports_thinking(&self, model: &str) -> bool {
        match self.show(model).await {
            Ok(doc) => doc
                .get("capabilities")
                .and_then(|c| c.as_array())
                .map(|arr| arr.iter().any(|v| v.as_str() == Some("thinking")))
                .unwrap_or(false),
            Err(_) => false,
        }
    }

    /// True if the model advertises the `vision` capability (Ollama `/api/show`
    /// `capabilities`). Used to route image input to a multimodal model and to
    /// warn when the selected model can't see images. Best-effort: false on any
    /// error (so we fail closed and prompt the user to pick a vision model).
    pub async fn supports_vision(&self, model: &str) -> bool {
        match self.show(model).await {
            Ok(doc) => doc
                .get("capabilities")
                .and_then(|c| c.as_array())
                .map(|arr| arr.iter().any(|v| v.as_str() == Some("vision")))
                .unwrap_or(false),
            Err(_) => false,
        }
    }

    fn build_chat_request(opts: &ChatOptions) -> ChatRequest {
        let options = ChatOptionsDto {
            temperature: opts.temperature,
            top_p: opts.top_p,
            num_ctx: opts.num_ctx,
        };

        ChatRequest {
            model: opts.model.clone(),
            messages: opts
                .messages
                .iter()
                .map(|m| ChatMessageDto {
                    role: m.role.clone(),
                    content: m.content.clone(),
                })
                .collect(),
            stream: opts.stream,
            options: Some(options)
                .filter(|o| o.temperature.is_some() || o.top_p.is_some() || o.num_ctx.is_some()),
        }
    }
}

#[async_trait::async_trait]
impl LlmProvider for OllamaProvider {
    fn name(&self) -> &str {
        "ollama"
    }

    async fn model_fingerprint(&self, model: &str) -> Option<String> {
        self.model_digest(model).await
    }

    async fn generate(&self, opts: GenerateOptions) -> Result<LlmResponse> {
        let start = Instant::now();
        let stream = opts.stream;
        let request = Self::build_generate_request(&opts);

        debug!("Generating with model: {} (stream={})", opts.model, stream);
        let endpoint = self.api_url("/api/generate");

        let response = self
            .client
            .post(endpoint.as_str())
            .json(&request)
            .send()
            .await
            .map_err(|e| ollama_error("send generate request to Ollama", &endpoint, e))?;

        if !response.status().is_success() {
            let status = response.status();
            let body = response
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            error!("Ollama returned error from {endpoint}: {status} - {body}");
            anyhow::bail!(
                "Ollama API error {status} from {endpoint}: {body}\n\
                Hint: is `ollama serve` running at {} and is the model `{}` pulled? \
                Try `ollama list` and `ollama pull {}`.",
                self.base_url,
                opts.model,
                opts.model
            );
        }

        // Ollama returns NDJSON when stream=true (one JSON object per line) and a
        // single JSON document when stream=false. `.json()` only handles the latter.
        let body = response
            .text()
            .await
            .map_err(|e| ollama_error("read generate response body from Ollama", &endpoint, e))?;
        let (content, model, eval_count, prompt_eval_count) = if stream {
            let mut buf = String::new();
            let mut last_model = opts.model.clone();
            let mut last_eval = None;
            let mut last_prompt_eval = None;
            for line in body.lines().filter(|l| !l.trim().is_empty()) {
                let chunk: GenerateResponse = serde_json::from_str(line).map_err(|e| {
                    ollama_error("parse generate NDJSON chunk from Ollama", &endpoint, e)
                })?;
                buf.push_str(&chunk.response);
                last_model = chunk.model;
                if chunk.done {
                    last_eval = chunk.eval_count;
                    last_prompt_eval = chunk.prompt_eval_count;
                }
            }
            (buf, last_model, last_eval, last_prompt_eval)
        } else {
            let result: GenerateResponse = serde_json::from_str(&body).map_err(|e| {
                ollama_error("parse generate JSON response from Ollama", &endpoint, e)
            })?;
            (
                result.response,
                result.model,
                result.eval_count,
                result.prompt_eval_count,
            )
        };

        let duration_ms = start.elapsed().as_millis() as u64;
        Ok(LlmResponse {
            content,
            model,
            tokens_generated: eval_count.unwrap_or(0),
            context_used: prompt_eval_count.unwrap_or(0),
            duration_ms,
        })
    }

    async fn chat(&self, opts: ChatOptions) -> Result<LlmResponse> {
        let start = Instant::now();
        let stream = opts.stream;
        let request = Self::build_chat_request(&opts);

        debug!("Chatting with model: {} (stream={})", opts.model, stream);
        let endpoint = self.api_url("/api/chat");

        let response = self
            .client
            .post(endpoint.as_str())
            .json(&request)
            .send()
            .await
            .map_err(|e| ollama_error("send chat request to Ollama", &endpoint, e))?;

        if !response.status().is_success() {
            let status = response.status();
            let body = response
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            error!("Ollama returned error from {endpoint}: {status} - {body}");
            anyhow::bail!(
                "Ollama API error {status} from {endpoint}: {body}\n\
                Hint: is `ollama serve` running at {} and is the model `{}` pulled?",
                self.base_url,
                opts.model
            );
        }

        let body = response
            .text()
            .await
            .map_err(|e| ollama_error("read chat response body from Ollama", &endpoint, e))?;
        let (content, model, eval_count, prompt_eval_count) = if stream {
            let mut buf = String::new();
            let mut last_model = opts.model.clone();
            let mut last_eval = None;
            let mut last_prompt_eval = None;
            for line in body.lines().filter(|l| !l.trim().is_empty()) {
                let chunk: ChatResponse = serde_json::from_str(line).map_err(|e| {
                    ollama_error("parse chat NDJSON chunk from Ollama", &endpoint, e)
                })?;
                buf.push_str(&chunk.message.content);
                last_model = chunk.model;
                if chunk.done {
                    last_eval = chunk.eval_count;
                    last_prompt_eval = chunk.prompt_eval_count;
                }
            }
            (buf, last_model, last_eval, last_prompt_eval)
        } else {
            let result: ChatResponse = serde_json::from_str(&body)
                .map_err(|e| ollama_error("parse chat JSON response from Ollama", &endpoint, e))?;
            (
                result.message.content,
                result.model,
                result.eval_count,
                result.prompt_eval_count,
            )
        };

        let duration_ms = start.elapsed().as_millis() as u64;
        Ok(LlmResponse {
            content,
            model,
            tokens_generated: eval_count.unwrap_or(0),
            context_used: prompt_eval_count.unwrap_or(0),
            duration_ms,
        })
    }

    async fn preload(&self, model: &str, keep_alive: &str) -> Result<()> {
        // Empty prompt + non-zero keep_alive = warm-load only.
        // See ollama/ollama docs: /api/generate with empty prompt loads the model.
        let req = GenerateRequest {
            model: model.to_string(),
            prompt: String::new(),
            system: None,
            stream: false,
            options: None,
            context: None,
            keep_alive: Some(keep_alive.to_string()),
            images: None,
            think: None,
            format: None,
        };
        // Per-call timeout: a 70B cold-load can legitimately take 60-90s,
        // so we go with 120s. The default client-wide timeout is 300s
        // which is too generous for the "model isn't installed and ollama
        // hangs trying to pull" failure mode.
        let endpoint = self.api_url("/api/generate");
        let resp = tokio::time::timeout(
            std::time::Duration::from_secs(120),
            self.client.post(endpoint.as_str()).json(&req).send(),
        )
        .await
        .map_err(|_| {
            anyhow::anyhow!(
                "preload of `{model}` at {endpoint} timed out after 120s. \
                 Is the model already pulled? Try `ollama pull {model}` first."
            )
        })?
        .map_err(|e| ollama_error("send preload request to Ollama", &endpoint, e))?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            anyhow::bail!(
                "Ollama preload of `{model}` failed with {status} from {endpoint}: {body}"
            );
        }
        Ok(())
    }

    async fn list_models(&self) -> Result<Vec<ModelInfo>> {
        let endpoint = self.api_url("/api/tags");
        let response = self
            .client
            .get(endpoint.as_str())
            .send()
            .await
            .map_err(|e| ollama_error("list models from Ollama", &endpoint, e))?;

        if !response.status().is_success() {
            let status = response.status();
            let body = response
                .text()
                .await
                .unwrap_or_else(|e| format!("<could not read Ollama error body: {e:#}>"));
            anyhow::bail!("list models from Ollama failed with {status} at {endpoint}: {body}");
        }

        let result: ModelsResponse = response
            .json()
            .await
            .map_err(|e| ollama_error("parse model list from Ollama", &endpoint, e))?;

        Ok(result
            .models
            .into_iter()
            .map(|m| ModelInfo {
                name: m.name,
                size: m.size,
                size_human: format_size(m.size),
                modified_at: m.modified_at,
                digest: m.digest,
            })
            .collect())
    }
}

fn format_size(bytes: u64) -> String {
    // Binary (1024-based) units, labeled correctly per IEC 80000-13.
    const KIB: u64 = 1024;
    const MIB: u64 = KIB * 1024;
    const GIB: u64 = MIB * 1024;

    if bytes >= GIB {
        format!("{:.1} GiB", bytes as f64 / GIB as f64)
    } else if bytes >= MIB {
        format!("{:.1} MiB", bytes as f64 / MIB as f64)
    } else if bytes >= KIB {
        format!("{:.1} KiB", bytes as f64 / KIB as f64)
    } else {
        format!("{} B", bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::{
        format_size, is_local_ollama_endpoint, normalize_ollama_endpoint, ollama_error,
        resolve_ollama_endpoint_with_host, LlmProvider, OllamaProvider, DEFAULT_OLLAMA_ENDPOINT,
    };
    use crate::providers::GenerateOptions;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    #[test]
    fn endpoint_normalization_accepts_host_only_values_and_removes_trailing_slashes() {
        assert_eq!(
            normalize_ollama_endpoint("localhost").unwrap(),
            "http://127.0.0.1:11434"
        );
        assert_eq!(
            normalize_ollama_endpoint("127.0.0.1:11555///").unwrap(),
            "http://127.0.0.1:11555"
        );
        assert_eq!(
            normalize_ollama_endpoint("https://ollama.example.test/").unwrap(),
            "https://ollama.example.test"
        );
    }

    #[test]
    fn endpoint_normalization_turns_bind_all_addresses_into_loopback() {
        assert_eq!(
            normalize_ollama_endpoint("0.0.0.0:11555").unwrap(),
            "http://127.0.0.1:11555"
        );
        assert_eq!(
            normalize_ollama_endpoint("http://[::]:11555/").unwrap(),
            "http://127.0.0.1:11555"
        );
        assert_eq!(
            normalize_ollama_endpoint("::").unwrap(),
            DEFAULT_OLLAMA_ENDPOINT
        );
        // An intentionally selected IPv6 loopback remains intact.
        assert_eq!(
            normalize_ollama_endpoint("[::1]:11555").unwrap(),
            "http://[::1]:11555"
        );
    }

    #[test]
    fn default_or_blank_endpoint_uses_ollama_host_but_explicit_remote_wins() {
        assert_eq!(
            resolve_ollama_endpoint_with_host("", Some("0.0.0.0:11435")).unwrap(),
            "http://127.0.0.1:11435"
        );
        assert_eq!(
            resolve_ollama_endpoint_with_host(
                "http://localhost:11434/",
                Some("remote.example:11436")
            )
            .unwrap(),
            "http://remote.example:11436"
        );
        assert_eq!(
            resolve_ollama_endpoint_with_host("https://remote.example/api/", Some("127.0.0.1"))
                .unwrap(),
            "https://remote.example/api"
        );
        assert_eq!(
            resolve_ollama_endpoint_with_host("  ", None).unwrap(),
            DEFAULT_OLLAMA_ENDPOINT
        );
    }

    #[test]
    fn provider_normalizes_its_explicit_endpoint_before_requests_are_built() {
        let provider = OllamaProvider::try_new("http://0.0.0.0:11555/").unwrap();
        assert_eq!(provider.base_url, "http://127.0.0.1:11555");
    }

    #[test]
    fn only_loopback_endpoints_bypass_proxy_settings() {
        assert!(is_local_ollama_endpoint("http://127.0.0.1:11434"));
        assert!(!is_local_ollama_endpoint("http://localhost:11434"));
        assert!(is_local_ollama_endpoint("http://[::1]:11434"));
        assert!(!is_local_ollama_endpoint("http://192.168.1.10:11434"));
        assert!(!is_local_ollama_endpoint("https://ollama.example.test"));
    }

    #[test]
    fn provider_errors_name_the_endpoint_and_preserve_the_root_cause_text() {
        let error = ollama_error(
            "list models from Ollama",
            "http://127.0.0.1:11434/api/tags",
            std::io::Error::other("connection refused"),
        );
        assert_eq!(
            format!("{error:#}"),
            "list models from Ollama at http://127.0.0.1:11434/api/tags: connection refused"
        );
    }

    #[tokio::test]
    async fn list_models_reaches_loopback_after_normalizing_a_bind_all_address() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        let server = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut request = Vec::new();
            let mut chunk = [0_u8; 512];
            while !request.windows(4).any(|window| window == b"\r\n\r\n") {
                let count = socket.read(&mut chunk).await.unwrap();
                assert_ne!(count, 0, "client closed before completing the request");
                request.extend_from_slice(&chunk[..count]);
            }
            assert!(
                String::from_utf8_lossy(&request).starts_with("GET /api/tags HTTP/1.1\r\n"),
                "unexpected request: {}",
                String::from_utf8_lossy(&request)
            );
            socket
                .write_all(
                    b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 13\r\nConnection: close\r\n\r\n{\"models\":[]}",
                )
                .await
                .unwrap();
        });

        let provider = OllamaProvider::try_new(format!("http://0.0.0.0:{port}/")).unwrap();
        assert!(provider.list_models().await.unwrap().is_empty());
        server.await.unwrap();
    }

    #[tokio::test]
    async fn streaming_generation_reaches_loopback_after_normalizing_a_bind_all_address() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        let server = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut request = Vec::new();
            let mut chunk = [0_u8; 512];
            while !request.windows(4).any(|window| window == b"\r\n\r\n") {
                let count = socket.read(&mut chunk).await.unwrap();
                assert_ne!(count, 0, "client closed before completing the request");
                request.extend_from_slice(&chunk[..count]);
            }
            assert!(
                String::from_utf8_lossy(&request).starts_with("POST /api/generate HTTP/1.1\r\n"),
                "unexpected request: {}",
                String::from_utf8_lossy(&request)
            );
            let body = concat!(
                "{\"response\":\"hello\",\"model\":\"test-coder\",\"done\":false}\n",
                "{\"response\":\"\",\"model\":\"test-coder\",\"done\":true}\n"
            );
            let response = format!(
                "HTTP/1.1 200 OK\r\nContent-Type: application/x-ndjson\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
                body.len()
            );
            socket.write_all(response.as_bytes()).await.unwrap();
        });

        let provider = OllamaProvider::try_new(format!("http://0.0.0.0:{port}/")).unwrap();
        let mut text = String::new();
        let bytes = provider
            .generate_streaming(
                GenerateOptions {
                    model: "test-coder".to_string(),
                    ..Default::default()
                },
                |piece| text.push_str(piece),
            )
            .await
            .unwrap();
        assert_eq!(text, "hello");
        assert_eq!(bytes, "hello".len());
        server.await.unwrap();
    }

    #[test]
    fn generate_request_includes_images_for_vision() {
        let opts = GenerateOptions {
            prompt: "what is in this image?".into(),
            images: Some(vec!["BASE64IMAGEDATA".into()]),
            ..Default::default()
        };
        let json = serde_json::to_string(&OllamaProvider::build_generate_request(&opts)).unwrap();
        assert!(json.contains("\"images\""));
        assert!(json.contains("BASE64IMAGEDATA"));
    }

    #[test]
    fn generate_request_omits_images_when_none() {
        let json = serde_json::to_string(&OllamaProvider::build_generate_request(
            &GenerateOptions::default(),
        ))
        .unwrap();
        assert!(
            !json.contains("images"),
            "images must be omitted when absent"
        );
    }

    #[test]
    fn generate_request_carries_think_only_when_set() {
        let on = GenerateOptions {
            think: Some(true),
            ..Default::default()
        };
        assert!(
            serde_json::to_string(&OllamaProvider::build_generate_request(&on))
                .unwrap()
                .contains("\"think\":true")
        );
        let off = serde_json::to_string(&OllamaProvider::build_generate_request(
            &GenerateOptions::default(),
        ))
        .unwrap();
        assert!(
            !off.contains("think"),
            "think must be omitted for non-reasoning models"
        );
    }

    #[test]
    fn response_parses_separate_thinking_stream() {
        let line = r#"{"response":"hi","thinking":"let me reason","model":"m","done":false}"#;
        let r: super::GenerateResponse = serde_json::from_str(line).unwrap();
        assert_eq!(r.thinking.as_deref(), Some("let me reason"));
        assert_eq!(r.response, "hi");
        // Absent thinking field still parses (non-reasoning models).
        let plain: super::GenerateResponse =
            serde_json::from_str(r#"{"response":"x","model":"m","done":true}"#).unwrap();
        assert!(plain.thinking.is_none());
    }

    #[test]
    fn format_size_uses_binary_units() {
        assert_eq!(format_size(0), "0 B");
        assert_eq!(format_size(1023), "1023 B");
        assert_eq!(format_size(1024), "1.0 KiB");
        assert_eq!(format_size(1024 * 1024), "1.0 MiB");
        assert_eq!(format_size(2 * 1024 * 1024 * 1024), "2.0 GiB");
    }
}
